[env:t-dongle-s3]
platform = https://github.com/cziter15/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
lib_deps =
  bblanchon/ArduinoJson@^7.1.0
  fastled/FastLED@^3.7.8
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DARDUINO_USB_MODE=0
board_build.embed_files =
  web/index.html
  web/settings.html

